baseURL = 'https://www.girtonball.com/'
languageCode = 'en-us'
title = 'GSB 2022'

disableKinds = ["taxonomy", "term"]

[params]
    description = "Welcome to the absurd world of the Girton Spring Ball! We are so excited to welcome you on Friday 18th March 2022!"